config/routes.rb
Bodypoint::Application.routes.draw do

	root to: 'pages#index'
	match '/company_overview', to: 'pages#company_overview'
	match '/company_overview_2', to: 'pages2#company_overview_2'
	match '/company_overview_940', to: 'pages2#company_overview_940'
	match '/company_overview_3', to: 'pages3#company_overview_3'
	match '/company_culture', to: 'pages#company_culture'
	match '/company_culture_2', to: 'pages2#company_culture_2'
	match '/company_culture_940', to: 'pages2#company_culture_940'
	match '/our_manifesto', to: 'pages#our_manifesto'
	match '/link_styles', to: 'pages#link_styles'
	match '/timeline', to: 'pages#timeline'
	match '/timeline_2', to: 'pages2#timeline_2'
	match '/whatcanbpdoforme_dealer', to: 'pages#whatcanbpdoforme_dealer'
	match '/whatcanbpdoforme_therapist', to: 'pages#whatcanbpdoforme_therapist'
	match '/whatcanbpdoforme_wheelchair_user', to: 'pages#whatcanbpdoforme_wheelchair_user'
	match '/images', to: 'pages#images'
	match '/how_to_buy', to: 'pages#how_to_buy'
	match '/how_to_become_a_partner', to: 'pages#how_to_become_a_partner'
	match '/privacy_policy', to: 'pages#privacy_policy'
	match '/wheelchair_positioning', to: 'pages#wheelchair_positioning'
	match '/why_positioning_matters', to: 'pages#why_positioning_matters'
	match '/terms_and_conditions', to: 'pages#terms_and_conditions'
	match '/faq', to: 'pages#faq'
	match '/literature', to: 'pages#literature'
	match '/coding', to: 'pages#coding'
	match '/find_a_partner', to: 'pages#find_a_partner'
	match '/find_a_partner_rep', to: 'pages#find_a_partner_rep'
	match '/find_a_partner_international', to: 'pages#find_a_partner_international'
	match '/success_stories_landing_page', to: 'pages#success_stories_landing_page'
	match '/aditya_story', to: 'pages#aditya_story'
	match '/alin_story', to: 'pages#alin_story'
	match '/barry_long_story', to: 'pages#barry_long_story'
	match '/hal_story', to: 'pages#hal_story'
	match '/todd_stabelfeldt_story', to: 'pages#todd_stabelfeldt_story'
	
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/page_2_controller.rb
class Page2Controller < ApplicationController

	def company_overview_2

	end

end

app/controllers/pages2_controller.rb
class Pages2Controller < ApplicationController

	def company_overview_2

	end

	def company_culture_2

	end

	def company_culture_940

	end

	def timeline_2

	end

end

app/controllers/pages3_controller.rb
class Pages3Controller < ApplicationController

	def company_overview_3

	end

end

app/controllers/pages_3_controller.rb
class Pages3Controller < ApplicationController

	def company_overview_3

	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def company_overview

	end

	def company_culture

	end

	def our_manifesto

	end

	def link_styles

	end

	def timeline

	end

	def whatcanbpdoforme_dealer

	end

	def whatcanbpdoforme_therapist

	end

	def whatcanbpdoforme_wheelchair_user

	end
	
	def images

	end

	def privacy_policy

	end

	def how_to_buy

	end

	def how_to_become_a_partner

	end

	def wheelchair_positioning

	end

	def why_positioning_matters
	
	end

	def terms_and_conditions

	end

	def privacy_policy

	end

	def faq

	end

	def literature

	end

	def coding

	end

	def find_a_partner

	end

	def success_stories_landing_page

	end

	def aditya_story

	end

	def alin_story

	end

	def barry_long_story

	end

	def hal_story

	end

	def todd_stabelfeldt_story

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_2_helper.rb
module Page2Helper
end

app/helpers/pages2_helper.rb
module Pages2Helper
end

app/helpers/pages3_helper.rb
module Pages3Helper
end

app/helpers/pages_3_helper.rb
module Pages3Helper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<img src="/assets/bodypoint_footer.jpg">
</div>

app/views/layouts/_navigation.html.erb
<div class="navigation">
	<img src="/assets/bodypoint_header.jpg">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bodypoint</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<%= render "layouts/navigation" %>

<%= yield %>

<%= render "layouts/footer" %>

</body>
</html>

app/views/pages/find_a_partner.html.erb
<div class="design_framework">

<div class="find_a_partner">

	<h1>How to Find a Partner</h1>

	<p>Bodypoint has partners all over the world that sell our products, support our channel and educate our customers about positioning. Click on a link below to find support in your area.</p>
<h2>U.S. Bodypoint Reseller</h2>
	<div class="find_a_partner_right">
		<div class="find_a_partner_map_links">
			<p><%= link_to "U.S. Bodypoint Reseller", find_a_partner_path %></p>
			<p><%= link_to "U.S. Bodypoint Representative", find_a_partner_rep_path, :id => "find_a_partner_map_links_representative" %></p>
			<p><%= link_to "International Partners", find_a_partner_international_path %></p>
		</div>
		<p>Still need help? <a href="#">Contact us.</a></p>
	</div>

	<div class="find_a_partner_map">
		
		<p>Search dealers by zip code, address or state</p>
		<img src="/assets/map_dealers.png">
		<p>View Dealers in a <a href="#">full screen map</a> </p>
	</div>

</div>

</div>

app/views/pages/find_a_partner_international.html.erb
<div class="design_framework">

<div class="find_a_partner">

	<h1>How to Find a Partner</h1>

	<p>Bodypoint has partners all over the world that sell our products, support our channel and educate our customers about positioning. Click on a link below to find support in your area.</p>
	<h2>International Partners</h2>
	<div class="find_a_partner_right">
		<div class="find_a_partner_map_links">
			<p><%= link_to "U.S. Bodypoint Reseller", find_a_partner_path %></p>
			<p><%= link_to "U.S. Bodypoint Representative", find_a_partner_rep_path, :id => "find_a_partner_map_links_representative" %></p>
			<p><%= link_to "International Partners", find_a_partner_international_path %></p>
		</div>
		<p>Still need help? <a href="#">Contact us.</a></p>
	</div>

	<div class="find_a_partner_map">
		
		<p>Search distributors by country or postcode</p>
		<img src="/assets/map_distributors.png">
		<p>View Bodypoint Distributors - International in a <a href="#">full screen map</a> </p>
	</div>

</div>

</div>

app/views/pages/find_a_partner_rep.html.erb
<div class="design_framework">

<div class="find_a_partner">

	<h1>How to Find a Partner</h1>

	<p>Bodypoint has partners all over the world that sell our products, support our channel and educate our customers about positioning. Click on a link below to find support in your area.</p>
	<h2>U.S. Bodypoint Representative</h2>
	<div class="find_a_partner_right">
		<div class="find_a_partner_map_links">
			<p><%= link_to "U.S. Bodypoint Reseller", find_a_partner_path %></p>
			<p><%= link_to "U.S. Bodypoint Representative", find_a_partner_rep_path, :id => "find_a_partner_map_links_representative" %></p>
			<p><%= link_to "International Partners", find_a_partner_international_path %></p>
		</div>
		<p>Still need help? <a href="#">Contact us.</a></p>
	</div>

	<div class="find_a_partner_map">
		
		<p>Search by state to locate a sales representative in your area</p>
		<img src="/assets/map_representatives.png">
		<p>View Bodypoint Sales Rep Groups in a <a href="#">full screen map</a> </p>
	</div>

</div>

</div>

app/views/pages/images.html.erb
<div class="index">

<h1>Images</h1>

<p></p>

<ol>

<h2>Company Culture Page</h2>
<p>Qoute: "we're a liitle different"</p>
	<li><img src="/assets/stock-photo-21765305-different-leader-best-unique-boss-individuality-original-special-concept.jpg"></li>
	<li><img src="/assets/chairs.jpg"></li>

<h2>What Can BP do for you Page therapists</h2>

	<li><img src="/assets/therapist1.jpg"></li>
	<li><img src="/assets/therapist2.jpg"></li>
	<li><img src="/assets/therapist3.jpg"></li>
	<li><img src="/assets/therapist4.jpg"></li>

<h2>What Can BP do for you Page Wheel Chair user</h2>
<p>this is the only one I have found that has a similar theme with other images you provided.  Everything I have found so far with these aren't really a good image to use or for the lack of a better word, cheesy, haha</p>
	<li><img src="/assets/wheelchair_user.jpg"></li>

<h2>What Can BP do for you Page Wheel Chair Dealer</h2>
	<p>So I have found nothing that I liked for this BUT I think I have found a solution. I was thinkning about taking one of these box images and photoshop at BP logo on it with the qoute to the left of it.  I'll make a sample image for it for you to get a idea of what I'm talking about.</p>

	<li><img src="/assets/box1.jpg"></li>
	<li><img src="/assets/box2.jpg"></li>
	<li><img src="/assets/box.jpg"></li>

</ol>

</div>

app/views/pages/index.html.erb
<div class="index">

<h1>New Page designs for BodyPoint</h1>

<p>

<h2>Images</h2>
<ul>
	<li><%= link_to "Images", images_path %></li>
</ul>

<h2>Company Overview Page</h2>

<ul>
	<li><%= link_to "Company Overview Version 1", company_overview_path %></li>
	<li><%= link_to "Company Overview Version 2", company_overview_2_path %></li>
	<li><%= link_to "Company Overview Version 2 PDF", "/Company_Overview_v2_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Company Overview Version 3", company_overview_3_path %></li>
	<li><%= link_to "Company Overview Version 3 PDF", "/Company_Overview_v3_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Company Overview Version 940", company_overview_940_path %></li>
	<li><%= link_to "Company Culture Version 940 PDF", "/Company_Oveview_940_Flynn.pdf", :target => "_blank" %></li>
</ul>

<p>

<h2>Company Culture Page</h2>
<ul>
	<li><%= link_to "Company Culture Version 1", company_culture_path %></li>
	<li><%= link_to "Company Culture Version 2", company_culture_2_path %></li>
	<li><%= link_to "Company Culture Version 2 PDF", "/Company_Culture_v2_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Company Culture Version 940", company_culture_940_path %></li>
	<li><%= link_to "Company Culture Version 940 PDF", "/Company_Culture_940_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Our Manifesto Page</h2>

<ul>
	<li><%= link_to "Our Manifesto Version 1", our_manifesto_path %></li>
	<li><%= link_to "Our Manifesto Version 1 PDF", "/Our_Manifesto_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Link Styles Page</h2>

<ul>
	<li><%= link_to "Link Styles", link_styles_path %></li>
	<li><%= link_to "Link Styles PDF", "/link_styles_flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Timeline Page</h2>

<ul>
	<li><%= link_to "Timeline", timeline_path %></li>
	<li><%= link_to "Timeline PDF", "/timeline_v1_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>What Can BP do for you Page</h2>

<ul>
	<li><%= link_to "Dealer", whatcanbpdoforme_dealer_path %></li>
	<li><%= link_to "Dealer PDF", "/whatcanbpdoforme_dealer_image_sample_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Therapists", whatcanbpdoforme_therapist_path %></li>
	<li><%= link_to "Therapists PDF", "/whatcanbpdoforme_therapist_v1_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Wheel Chair Users", whatcanbpdoforme_wheelchair_user_path %></li>
	<li><%= link_to "Wheel Chair Users PDF", "/whatcanbpdoforme_wheelchair_user_v1_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>How To Buy</h2>

<ul>
	<li><%= link_to "How To Buy", how_to_buy_path %></li>
	<li><%= link_to "How To Buy PDF", "/how_to_buy_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Partner Center</h2>

<ul>
	<li><%= link_to "How to become a Partner", how_to_become_a_partner_path %></li>
	<li><%= link_to "How to become a Partner PDF", "/partner_center_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Wheelchair Positioning</h2>

<ul>
	<li><%= link_to "Wheelchair Positioning", wheelchair_positioning_path %></li>
	<li><%= link_to "Wheelchair Positioning PDF", "/wheelchair_positioning_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Why Positioning Matters</h2>

<ul>
	<li><%= link_to "Why Positioning Matters", why_positioning_matters_path %></li>
	<li><%= link_to "Why Positioning Matters PDF", "/why_positioning_matters_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Terms and Conditions</h2>

<ul>
	<li><%= link_to "Terms and Conditions", terms_and_conditions_path %></li>
	<li><%= link_to "Terms and Conditions PDF", "/terms_and_conditions_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Privacy Policy</h2>

<ul>
	<li><%= link_to "Privacy Policy", privacy_policy_path %></li>
	<li><%= link_to "Privacy Policy PDF", "/privacy_policy_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>FAQ</h2>

<ul>
	<li><%= link_to "FAQ", faq_path %></li>
	<li><%= link_to "FAQ PDF", "/faq_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Literature</h2>

<ul>
	<li><%= link_to "Literature", literature_path %></li>
	<li><%= link_to "Literature PDF", "/literature_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Coding page</h2>

<ul>
	<li><%= link_to "Coding page", coding_path %></li>
	<li><%= link_to "Coding page PDF", "/coding_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Find a Partner</h2>

<ul>
	<li><%= link_to "Find a Partner", find_a_partner_path %></li>
	<li><%= link_to "Find a Partner PDF", "/find_a_partner_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Find a Representative", find_a_partner_rep_path %></li>
	<li><%= link_to "Find a Representative PDF", "/find_a_partner_representative_Flynn.pdf", :target => "_blank" %></li>
	<li><%= link_to "Find a International Partner", find_a_partner_international_path %></li>
	<li><%= link_to "Find a International Partner PDF", "/find_a_partner_international_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Success Story Landing page</h2>

<ul>
	<li><%= link_to "Success Story Landing page", success_stories_landing_page_path %></li>
	<li><%= link_to "Success Story Landing page PDF", "/success_stories_landing_page_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Aditya Story</h2>

<ul>
	<li><%= link_to "Aditya Story", aditya_story_path %></li>
	<li><%= link_to "Aditya Story page PDF", "/aditya_story_Flynn.pdf", :target => "_blank" %></li>
</ul>

<h2>Alin Story</h2>

<ul>
	<li><%= link_to "Alin Story", alin_story_path %></li>
	<li><%= link_to "Alin Story page PDF", "/alin_story_Flynn.pdf", :target => "_blank" %></li>
</ul>


<h2>Barry Long Story</h2>

<ul>
	<li><%= link_to "Barry Long Story", barry_long_story_path %></li>
	<li><%= link_to "Barry Long Story PDF", "/barry_long_story_Flynn.pdf", :target => "_blank" %></li>
</ul>


<h2>Hal Story</h2>

<ul>
	<li><%= link_to "Hal Story", hal_story_path %></li>
	<li><%= link_to "Hal Story PDF", "/hal_story_Flynn.pdf", :target => "_blank" %></li>
</ul>


<h2>Todd Stabelfeldt Story</h2>

<ul>
	<li><%= link_to "Todd Stabelfeldt Story", todd_stabelfeldt_story_path %></li>
	<li><%= link_to "Todd Stabelfeldt Story PDF", "/todd_stabelfeldt_story_Flynn.pdf", :target => "_blank" %></li>
</ul>



</div>

</div>